### ISSUE TITLE
'NoneType' object has no attribute 'META'

### ISSUE THREAD

**Issue by 9mido** [un33k/django-ipware#69]
I am trying to use the request object in a forms.py file. Yes, this is out of the ordinary but for my use case I need it.

These are some examples I am following:

https://stackoverflow.com/questions/2683689/django-access-request-object-from-admins-form-clean

https://stackoverflow.com/questions/1057252/how-do-i-access-the-request-object-or-any-other-variable-in-a-forms-clean-met

This problem seems to derive from:
`self.request = kwargs.pop('request', None)`

and using 

`get_client_ip(self.request)` or `get_client_ip(request)`

Trying not to override the view of the third party app I am using.

```
Traceback (most recent call last):
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/allauth/account/views.py", line 101, in post
    if form.is_valid():
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/forms/forms.py", line 373, in full_clean
    self._clean_form()
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/forms/forms.py", line 400, in _clean_form
    cleaned_data = self.clean()
  File "/home/name/video-membership-master/courses/forms.py", line 624, in clean
    ip, is_routable = get_client_ip(self.request)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/ipware/ip.py", line 25, in get_client_ip
    value = util.get_request_meta(request, key)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/ipware/utils.py", line 76, in get_request_meta
    value = request.META.get(key, request.META.get(key.replace('_', '-'), '')).strip()
AttributeError: 'NoneType' object has no attribute 'META'
```

**Comment by un33k** [comment]
The proper use of `ipware` is to pass in the incoming request that WILL have the META attribute.  After all, the is to return the IP address and the incoming `request` MUST have the META attribute, or no point in using `ipware`. 

However, for overloading use cases, one can do this .. 

```python
try:
  get_client_ip(request)
except NoneType:
  pass #  we know what we are doing.
```

OR  `something` like below.

```python
if not request.META:
  request.META = {}
get_client_ip(request)
```

**Comment by un33k** [comment]
After reading the traceback I see that his is the line that is failing here .. 

```python
self.request = kwargs.pop('request', None)
```

The above line is trying to grab the request or `None`, and so `None` is returned. 

The error clearly indicates the `None` value for the request.
```python
AttributeError: 'NoneType' object has no attribute 'META'
```

If we pass in `None` to `get_client_ip()` and should expect an error.
